FROM kalilinux/kali-rolling

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    net-tools python3 python3-pip \
    apt-transport-https \
    ca-certificates \
    openssh-server openssh-client \
    curl whatweb seclists openvpn \
    ftp \
    dnsutils \
    whois \
    exploitdb \
    hydra \
    iputils-ping \
    nmap \
    nikto \
    gobuster \
    dirb \
    smbclient \
    tmux \
    wget \
    netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && chmod 755 msfinstall && ./msfinstall

CMD ["sleep", "infinity"]